---
- name: CREATING Configuration file
  template:
    src: php72.conf.j2
    dest: "{{ php72_config }}"
    owner: root
    group: root
    setype: php72_config_t
    mode: '0644'
  notify: restart php72
  tags: php72
