---
- name: 'HANLDER - Restart PHP 7.2'
  become: yes
  service:
    name: php72-php-fpm
    state: restarted
  listen: "restart php72"

- name: 'HANDLER - Restart NGINX'
  become: yes
  service:
    name: nginx
    state: restarted
  listen: "restart nginx"
