---
- name: 'CREATING New NGINX Configuration file + Backup'
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_config }}"
    owner: root
    group: root
    setype: nginx_config_t
    mode: '0644'
    backup: True
    validate: 'nginx -t -c %s'
  notify: restart nginx
  tags: nginx


