---
- name: 'VALIDATING - NGINX Cache_dir: {{ nginx_cache_dir }} exists'
  become: True
  file:
    state: directory  
    path: '{{ nginx_cache_dir }}'
    owner: 'root'
    group: 'root'
    mode: 0755




- name: 'CREATING - NGINX Config file: "{{ nginx_config }}" + Backup + Validation'
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_config }}"
    owner: root
    group: root
    setype: nginx_config_t
    mode: '0644'
    backup: True
    validate: 'nginx -t -c %s'
  notify: restart nginx
  tags: nginx
