---
- name: 'CREATING - Blog directory: "/www/var/html/blog"'
  become: yes
  file:
    path: "/www/var/html/blog"
    state: directory

- name: 'COPYING -  Wordpress Dir: "/usr/share/wordpress" --> "/www/var/html/blog/"'
  become: yes
  command: "cp -ar /usr/share/wordpress/ /var/www/html/blog/"
