---
- name: Creates "/www/var/html/blog" directory 
  become: yes
  file:
    path: "/www/var/html/blog"
    state: directory

- name: Copy Wordpress Dir to "/www/var/html/blog"
  become: yes
  command: "cp -ar /usr/share/wordpress/ /var/www/html/blog/"
