---
auth_key_dir: "/etc/ssh/authorized_keys"

users:
  - username: wordpress_dev
    use_sudo: true
    ssh_access: true
    ssh_pub_key: "{{ lookup('file', 'wordpress_dev.pub' ) }}"

 
yum_packages:
  - epel-release
  - nginx
  - tree
  - htop
  - tcpdump
  - traceroute


start_services:
  - nginx
