---
- include_tasks: yum_p.yaml

- include_tasks: start_services.yaml
  when: "start_serv is defined"

- include_tasks: enable_services.yaml
  when: "enable_serv is defined"

- include_tasks: httpd_config.yaml
