---
yum_packs:
  - nginx

start_serv:
  - nginx

enable_serv:
  - nginx

nginx_config: "/etc/nginx/nginx.conf"
nginx_user: "nginx"
nginx_errorlog: "/var/log/nginx/error_log"
nginx_accesslog: "/var/log/nginx/access_log"
nginx_enable_gzip: True
nginx_cache_dir: '/usr/share/nginx/cache/fcgi'

nginx_server_http_ipv4_listen: "*:80 default_server"
nginx_server_http_ipv6_listen: "[::]:80 default_server"

nginx_server_root: "/usr/share/nginx/html"

nginx_enable_ssl: True
# The following block needs to be defined if nginx_enable_ssl: True
nginx_server_https_ipv4_listen: "*:443 ssl http2"
nginx_server_https_ipv6_listen: "[::]:443 ssl http2"
